# Configuraci칩n b치sica del sitio
 title: 'Pagina prueba.'
 description: 'Pagina de prueba usando Git y GitHub con base en Jekyll.'
 baseurl: "/pruebaPAG.github.io"
 url: "https://zotexd.github.io"
 markdown: kramdown
# Permalink para posts normales (m치s limpio, sin fecha)
 permalink: /:title/

 #El output: true es para que se generen las p치ginas HTML de cada post.
 #Los marcados con "#*" son para indicar que esta creada esa carpeta y evitar errores.
 collections:
  ririsa:
  ririsa: #*
    output: true 
    permalink: /ririsa/:title/
  saneka: #*
    output: true
    permalink: /saneka/:title/
  100novias:
  100novias: #*
    output: true
    permalink: /100novias/:title/